### ISSUE TITLE
기상청 API 사용 - 현재 날씨, 기온 main fragment에 표시

### ISSUE THREAD

**Issue by MontyCoder0701** [soojlee0106/FashionApp#1]
보라매 기준의 현 기온,  날씨와 그에 맞는 아이콘을 홈화면에 보여줍니다.

**Comment by kkimhaji** [comment]
GET 방식

### 좌표

(SK 텔레콤 보라매 사옥 기준)

37.492081

126.926039

### 날짜 및 시간

- 날짜: 실행기준 날짜 받아오기
- 시간: 현재 시간 받아오기
- 단기 예보로 진행

### 타입

json
