### ISSUE TITLE
11번가 검색 api 연결

### ISSUE THREAD

**Issue by kkimhaji** [soojlee0106/FashionApp#24]
## 11번가 검색 open api 연결

- [x] 발급신청 - 상품 조회 api
- [x] api 연결 후 결과 조회
- [x] 키워드 fragment 간 변수로 넘겨받기 (모델 완료 후)
- [x] 검색 결과 horizontal scroll view 에 넣기
- [x] view adapter로 여러 개 ui 생성
- [x] 해당 결과 클릭 시 사이트(상품 페이지)로 이동
- [x] 다른 옷 찾아보기 클릭 시 키워드 중 다른 값 랜덤으로 가져오기
- [x] 만약 키워드 리스트의 사이즈 = 0이면 초기의 키워드 값으로 초기화

**Comment by MontyCoder0701** [comment]
https://developers.naver.com/docs/serviceapi/search/shopping/shopping.md

**Comment by kkimhaji** [comment]
[x] 다른 옷 찾아보기 클릭 시 keyword 중에서 다른 값 가져오기
[ ] 키워드 리스트 사이즈 = 0이면 초기값 다시 넣기
